apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: sb-demo
type: Opaque
data:
  POSTGRES_USER: dXNlcg==
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  SPRING_DATASOURCE_USERNAME: dXNlcg==
  SPRING_DATASOURCE_PASSWORD: cGFzc3dvcmQ=
